version: '3'

services:
  db:
    image: mysql
    container_name: db_mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: